openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://test-project.test'
paths:
  /api/accounts:
    post:
      summary: 'Accounts create.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 201
                  locale: en
                  message: OK
                  data:
                    account:
                      name: 'Stoltenberg, Ratke and Wyman'
                      description: 'Laudantium impedit cupiditate est. Earum ratione dolorem delectus totam. Iusto repellendus dolor atque delectus dolorum sunt at.'
                      address: "35596 Lila Prairie\nPort Chauncey, LA 80430-0752"
                      postal_code: '54129'
                      city: Skileshaven
                      is_active: 1
                      country_code: GG
                      user_id: 1
                      updated_at: '2021-11-22T14:11:05.000000Z'
                      created_at: '2021-11-22T14:11:05.000000Z'
                      id: 1
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 201
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      account:
                        name: 'Stoltenberg, Ratke and Wyman'
                        description: 'Laudantium impedit cupiditate est. Earum ratione dolorem delectus totam. Iusto repellendus dolor atque delectus dolorum sunt at.'
                        address: "35596 Lila Prairie\nPort Chauncey, LA 80430-0752"
                        postal_code: '54129'
                        city: Skileshaven
                        is_active: 1
                        country_code: GG
                        user_id: 1
                        updated_at: '2021-11-22T14:11:05.000000Z'
                        created_at: '2021-11-22T14:11:05.000000Z'
                        id: 1
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: dd
                description:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ''
                address:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: v
                postal_code:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: r
                city:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: r
                is_active:
                  type: string
                  description: ''
                  example: in
                country_code:
                  type: string
                  description: ''
                  example: null
                user_id:
                  type: integer
                  description: ''
                  example: 7
              required:
                - name
                - is_active
                - user_id
    get:
      summary: 'Accounts return all.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    accounts:
                      current_page: 1
                      data: []
                      first_page_url: 'http://example.test/api/accounts?page=1'
                      from: null
                      last_page: 1
                      last_page_url: 'http://example.test/api/accounts?page=1'
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://example.test/api/accounts?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      next_page_url: null
                      path: 'http://example.test/api/accounts'
                      per_page: 10
                      prev_page_url: null
                      to: null
                      total: 0
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      accounts:
                        current_page: 1
                        data: []
                        first_page_url: 'http://example.test/api/accounts?page=1'
                        from: null
                        last_page: 1
                        last_page_url: 'http://example.test/api/accounts?page=1'
                        links:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://example.test/api/accounts?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        next_page_url: null
                        path: 'http://example.test/api/accounts'
                        per_page: 10
                        prev_page_url: null
                        to: null
                        total: 0
      tags:
        - Endpoints
  '/api/accounts/{id}':
    get:
      summary: 'Accounts shows single .'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    account:
                      id: 1
                      name: 'Corwin Ltd'
                      user_id: '1'
                      description: 'Molestias deserunt sed tenetur nostrum neque sed blanditiis. Quod consequatur quibusdam aut. Dolore quia vitae cum quae quisquam quia. Fuga rerum unde ipsa.'
                      address: "24764 Walter Brooks\nLake Gracie, OK 50893"
                      city: Schaeferton
                      postal_code: 38625-7681
                      country_code: WS
                      is_active: '1'
                      created_at: '2021-11-22T14:28:29.000000Z'
                      updated_at: '2021-11-22T14:28:29.000000Z'
                      contacts: []
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      account:
                        id: 1
                        name: 'Corwin Ltd'
                        user_id: '1'
                        description: 'Molestias deserunt sed tenetur nostrum neque sed blanditiis. Quod consequatur quibusdam aut. Dolore quia vitae cum quae quisquam quia. Fuga rerum unde ipsa.'
                        address: "24764 Walter Brooks\nLake Gracie, OK 50893"
                        city: Schaeferton
                        postal_code: 38625-7681
                        country_code: WS
                        is_active: '1'
                        created_at: '2021-11-22T14:28:29.000000Z'
                        updated_at: '2021-11-22T14:28:29.000000Z'
                        contacts: []
      tags:
        - Endpoints
    put:
      summary: 'Accounts updates an existing .'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    account:
                      id: 1
                      name: 'Schiller Inc'
                      user_id: '1'
                      description: 'Voluptate modi facere adipisci maxime quo. Facere a ut sed aperiam. Minus deserunt ab dolor iusto qui vero praesentium. Consequatur ut consequatur optio magni odio deleniti.'
                      address: "3386 Tevin Shores Apt. 749\nDouglasborough, VT 51354-9497"
                      city: 'South Laruefurt'
                      postal_code: '98006'
                      country_code: KE
                      is_active: '1'
                      created_at: '2021-11-22T14:13:35.000000Z'
                      updated_at: '2021-11-22T14:13:35.000000Z'
                      contacts: []
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      account:
                        id: 1
                        name: 'Schiller Inc'
                        user_id: '1'
                        description: 'Voluptate modi facere adipisci maxime quo. Facere a ut sed aperiam. Minus deserunt ab dolor iusto qui vero praesentium. Consequatur ut consequatur optio magni odio deleniti.'
                        address: "3386 Tevin Shores Apt. 749\nDouglasborough, VT 51354-9497"
                        city: 'South Laruefurt'
                        postal_code: '98006'
                        country_code: KE
                        is_active: '1'
                        created_at: '2021-11-22T14:13:35.000000Z'
                        updated_at: '2021-11-22T14:13:35.000000Z'
                        contacts: []
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ''
                description:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ''
                address:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: j
                postal_code:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ''
                city:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: qj
                is_active:
                  type: string
                  description: ''
                  example: asperiores
                country_code:
                  type: string
                  description: ''
                  example: null
                user_id:
                  type: integer
                  description: ''
                  example: 3
              required:
                - name
                - is_active
                - user_id
    delete:
      summary: 'Accounts deletes an existing.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    value: 'Account successfully deleted'
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      value: 'Account successfully deleted'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the account.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/contacts/{id}':
    get:
      summary: 'Contact Shows single .'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    contact:
                      id: 1
                      account_id: '1'
                      first_name: Talon
                      last_name: Bahringer
                      job_title: 'Plating Machine Operator'
                      address: "94628 Craig Shoals\nHarveyfort, RI 01412-6293"
                      city: Abbyhaven
                      postal_code: 82793-5888
                      country_code: HK
                      email: isaiah.bogisich@gmail.com
                      phone: +1-351-936-2170
                      created_at: '2021-11-22T20:42:08.000000Z'
                      updated_at: '2021-11-22T20:42:08.000000Z'
                      account:
                        id: 1
                        name: 'Parisian PLC'
                        user_id: '1'
                        description: 'Minima quia quod natus. Enim aspernatur in iure doloribus distinctio aut fuga. Iste est distinctio recusandae enim molestias saepe. Sed omnis eligendi sunt.'
                        address: "618 Gulgowski Squares\nSouth Christophe, CA 47461"
                        city: 'South Dakota'
                        postal_code: 62172-5816
                        country_code: RS
                        is_active: '1'
                        created_at: '2021-11-22T20:42:08.000000Z'
                        updated_at: '2021-11-22T20:42:08.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      contact:
                        id: 1
                        account_id: '1'
                        first_name: Talon
                        last_name: Bahringer
                        job_title: 'Plating Machine Operator'
                        address: "94628 Craig Shoals\nHarveyfort, RI 01412-6293"
                        city: Abbyhaven
                        postal_code: 82793-5888
                        country_code: HK
                        email: isaiah.bogisich@gmail.com
                        phone: +1-351-936-2170
                        created_at: '2021-11-22T20:42:08.000000Z'
                        updated_at: '2021-11-22T20:42:08.000000Z'
                        account:
                          id: 1
                          name: 'Parisian PLC'
                          user_id: '1'
                          description: 'Minima quia quod natus. Enim aspernatur in iure doloribus distinctio aut fuga. Iste est distinctio recusandae enim molestias saepe. Sed omnis eligendi sunt.'
                          address: "618 Gulgowski Squares\nSouth Christophe, CA 47461"
                          city: 'South Dakota'
                          postal_code: 62172-5816
                          country_code: RS
                          is_active: '1'
                          created_at: '2021-11-22T20:42:08.000000Z'
                          updated_at: '2021-11-22T20:42:08.000000Z'
      tags:
        - Endpoints
    put:
      summary: 'Contact Updates an existing.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    contact:
                      id: 1
                      account_id: 1
                      first_name: Juvenal
                      last_name: Yost
                      job_title: 'Transformer Repairer'
                      address: "2615 Kaley Lodge\nEast Alfonsotown, CT 70458-6001"
                      city: Haagport
                      postal_code: '14234'
                      country_code: FO
                      email: newton43@keeling.com
                      phone: +1-541-245-6893
                      created_at: '2021-11-22T20:42:42.000000Z'
                      updated_at: '2021-11-22T20:42:42.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      contact:
                        id: 1
                        account_id: 1
                        first_name: Juvenal
                        last_name: Yost
                        job_title: 'Transformer Repairer'
                        address: "2615 Kaley Lodge\nEast Alfonsotown, CT 70458-6001"
                        city: Haagport
                        postal_code: '14234'
                        country_code: FO
                        email: newton43@keeling.com
                        phone: +1-541-245-6893
                        created_at: '2021-11-22T20:42:42.000000Z'
                        updated_at: '2021-11-22T20:42:42.000000Z'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: gd
                last_name:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: e
                job_title:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ''
                account_id:
                  type: integer
                  description: ''
                  example: 19
                postal_code:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ki
                city:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: cp
                address:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: i
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: kshlerin.gustave@example.net
                country_code:
                  type: string
                  description: ''
                  example: null
              required:
                - first_name
                - last_name
                - account_id
    delete:
      summary: 'Contact Deletes an existing.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    value: 'Contact successfully deleted'
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      value: 'Contact successfully deleted'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the contact.'
        example: 17
        required: true
        schema:
          type: integer
  /api/notes:
    get:
      summary: 'Notes returns all .'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    notes:
                      current_page: 1
                      data: []
                      first_page_url: 'http://example.test/api/notes?page=1'
                      from: null
                      last_page: 1
                      last_page_url: 'http://example.test/api/notes?page=1'
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://example.test/api/notes?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      next_page_url: null
                      path: 'http://example.test/api/notes'
                      per_page: 10
                      prev_page_url: null
                      to: null
                      total: 0
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      notes:
                        current_page: 1
                        data: []
                        first_page_url: 'http://example.test/api/notes?page=1'
                        from: null
                        last_page: 1
                        last_page_url: 'http://example.test/api/notes?page=1'
                        links:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://example.test/api/notes?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        next_page_url: null
                        path: 'http://example.test/api/notes'
                        per_page: 10
                        prev_page_url: null
                        to: null
                        total: 0
      tags:
        - Endpoints
    post:
      summary: 'Note creates a new .'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 201
                  locale: en
                  message: OK
                  data:
                    note:
                      body: 'Then they both bowed low, and their curls got entangled together. Alice was beginning to grow up any more HERE.'' ''But then,'' thought Alice, ''or perhaps they won''t walk the way I ought to have him.'
                      noteable_id: 1
                      noteable_type: account
                      noteable:
                        id: 1
                        name: 'O''Connell-Hansen'
                        user_id: '1'
                        description: 'Omnis sit voluptas placeat officiis mollitia tenetur voluptatibus accusantium. Quia non vero magnam impedit eos commodi voluptatem. Et esse nihil ut dolore error fugit perspiciatis.'
                        address: "888 Reinger Turnpike Suite 784\nDevonbury, NV 75167"
                        city: 'East Domingo'
                        postal_code: '67072'
                        country_code: AU
                        is_active: '1'
                        created_at: '2021-11-22T20:44:53.000000Z'
                        updated_at: '2021-11-22T20:44:53.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 201
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      note:
                        body: 'Then they both bowed low, and their curls got entangled together. Alice was beginning to grow up any more HERE.'' ''But then,'' thought Alice, ''or perhaps they won''t walk the way I ought to have him.'
                        noteable_id: 1
                        noteable_type: account
                        noteable:
                          id: 1
                          name: 'O''Connell-Hansen'
                          user_id: '1'
                          description: 'Omnis sit voluptas placeat officiis mollitia tenetur voluptatibus accusantium. Quia non vero magnam impedit eos commodi voluptatem. Et esse nihil ut dolore error fugit perspiciatis.'
                          address: "888 Reinger Turnpike Suite 784\nDevonbury, NV 75167"
                          city: 'East Domingo'
                          postal_code: '67072'
                          country_code: AU
                          is_active: '1'
                          created_at: '2021-11-22T20:44:53.000000Z'
                          updated_at: '2021-11-22T20:44:53.000000Z'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: da
                noteable_type:
                  type: string
                  description: ''
                  example: reprehenderit
                noteable_id:
                  type: integer
                  description: ''
                  example: 7
              required:
                - body
                - noteable_type
                - noteable_id
  /api/contacts:
    get:
      summary: 'Contacts Returns all.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 200
                  locale: en
                  message: OK
                  data:
                    contacts:
                      current_page: 1
                      data: []
                      first_page_url: 'http://example.test/api/contacts?page=1'
                      from: null
                      last_page: 1
                      last_page_url: 'http://example.test/api/contacts?page=1'
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://example.test/api/contacts?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      next_page_url: null
                      path: 'http://example.test/api/contacts'
                      per_page: 10
                      prev_page_url: null
                      to: null
                      total: 0
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      contacts:
                        current_page: 1
                        data: []
                        first_page_url: 'http://example.test/api/contacts?page=1'
                        from: null
                        last_page: 1
                        last_page_url: 'http://example.test/api/contacts?page=1'
                        links:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://example.test/api/contacts?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        next_page_url: null
                        path: 'http://example.test/api/contacts'
                        per_page: 10
                        prev_page_url: null
                        to: null
                        total: 0
      tags:
        - Endpoints
    post:
      summary: 'Contacts Stores newly created.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  code: 201
                  locale: en
                  message: OK
                  data:
                    contact:
                      id: 1
                      first_name: Adelia
                      last_name: Legros
                      account_id: 1
                      postal_code: 43201-4839
                      city: Kiehnfurt
                      address: "4288 Amalia Pine Suite 107\nAndreannemouth, KS 14490-1489"
                      email: pfeffer.angus@cassin.com
                      country_code: VI
                      updated_at: '2021-11-22T20:40:56.000000Z'
                      created_at: '2021-11-22T20:40:56.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 201
                  locale:
                    type: string
                    example: en
                  message:
                    type: string
                    example: OK
                  data:
                    type: object
                    example:
                      contact:
                        id: 1
                        first_name: Adelia
                        last_name: Legros
                        account_id: 1
                        postal_code: 43201-4839
                        city: Kiehnfurt
                        address: "4288 Amalia Pine Suite 107\nAndreannemouth, KS 14490-1489"
                        email: pfeffer.angus@cassin.com
                        country_code: VI
                        updated_at: '2021-11-22T20:40:56.000000Z'
                        created_at: '2021-11-22T20:40:56.000000Z'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: 'n'
                last_name:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ny
                job_title:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: af
                account_id:
                  type: integer
                  description: ''
                  example: 10
                postal_code:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: wm
                city:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: t
                address:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: ''
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: xgreenfelder@example.org
                country_code:
                  type: string
                  description: ''
                  example: null
              required:
                - first_name
                - last_name
                - account_id
  /api/login:
    post:
      summary: 'Login - Generates a jwt token'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"data\": {\n \"access_token\": \"eyJ0eXA...\",\n \"token_type\": \"Bearer\",\n  \"expires_at\": \"2022-...\"\n}"
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: qmoen@example.com
                password:
                  type: string
                  description: ''
                  example: repellendus
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
